### ISSUE TITLE
Re-rendering failing with `conda-build` version `24.7.1`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cuda-nvdisasm-feedstock#12]
We are seeing issues re-rendering with this feedstock ( https://github.com/conda-forge/cuda-nvdisasm-feedstock/pull/11#issuecomment-2265437200 ). Also seeing in several other CTK feedstocks

It looks like logic like this is where re-rendering has issues

https://github.com/conda-forge/cuda-nvdisasm-feedstock/blob/659d7dfb1e9be90dbb56a84a519a2f94c8a6e5f4/recipe/meta.yaml#L4-L7

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
Filed upstream issue: https://github.com/conda-forge/conda-smithy/issues/2011

**Comment by jakirkham** [comment]
cc @msarahan (for looking into this a bit more)

**Comment by msarahan** [comment]
Reverting this commit fixes it: https://github.com/conda/conda-build/commit/87194f681b8c50a2502bdf5a60c5ffe8e08281ab

Haven't isolated exactly which part yet.

**Comment by msarahan** [comment]
https://github.com/conda/conda-build/pull/5458

**Comment by jakirkham** [comment]
This was fixed in conda-build 24.9.0 with Michael's PR. Closing as resolved
